### PR TITLE
Added folia support with UniversalScheduler

### PR DESCRIPTION
**Pull request by Deichor**
I've made all schedulers compatible with both Spigot and Folia using UniversalScheduler. I've conducted a few tests, and everything seems to be working smoothly at the moment.

### CODE REVIEW

**Comment by erikzimmermann** [comment]
Somehow this PR includes lots of changes that I did since this PR was opened... I'd merge this once this has been resolved.

Thanks for contributing!

**Review by erikzimmermann — CHANGES_REQUESTED** [review]
Please only include changes targeting the UniversalScheduler.

**Comment by erikzimmermann** [comment]
Addresses #483

**Comment by Deichor** [comment]
In order to fully support Folia, CodingAPI also needed to support Folia first. You can ignore the other changes I made; they were just to test pulling the Folia version of CodingAPI.

**Comment by erikzimmermann** [comment]
Your changes to CodingAPI are already merged :)

**Comment by Deichor** [comment]
I've configured the setup files for the original codingapi and updated a few things. From now on, you don’t need to call it with Bukkit.getScheduler. However, when you call it with UniversalScheduler, you might sometimes need to use location. This means that if you need to access something like a block or chunk, you’ll need to access its thread. But since these processes are generally handled within the codingapi part, I don’t think you’ll encounter any issues.

**Pull request merged**
