### PR TITLE
Better bedrock input

### PR DESCRIPTION
**Pull request by masmc05**
Fix https://github.com/erikzimmermann/TradeSystem/issues/492
Fix https://github.com/erikzimmermann/TradeSystem/issues/496
Maybe a fix for https://github.com/erikzimmermann/TradeSystem/issues/467 since it also could be related to bedrock

This allows bedrock players to have an alternative input that will allow them to enter the sum to trade, since the sign and anvil are a bit broken on bedrock

### CODE REVIEW

**Comment by erikzimmermann** [comment]
First of all, thank you for your work! Do you maybe have some image of how the input looks like? Is is an actuall slider?

**Comment by ezriharmusial** [comment]
I have also noticed that i can not trade with Bedrock players. Deal gets cancelled after both partys agree to the trade. Is this a Correct observation?

**Comment by masmc05** [comment]
> First of all, thank you for your work! Do you maybe have an image of how the input looks like? Is it an actuall slider?

image
image
image

Here are some screenshots

**Comment by masmc05** [comment]
> I have also noticed that i can not trade with Bedrock players. Deal gets cancelled after both partys agree to the trade. Is this a Correct observation?

With this pr you can

**Comment by masmc05** [comment]
You can read more about them on https://geysermc.ru/wiki/floodgate/forms-and-cumulus

**Review by erikzimmermann — APPROVED** [review]

**Comment by erikzimmermann** [comment]
> I have also noticed that i can not trade with Bedrock players. Deal gets cancelled after both partys agree to the trade. Is this a Correct observation?

Well, this is caused by the countdown I guess. Updating GUI titles seem to crash the inventory on bedrock clients... Will be fixed in the next update tho.

**Comment by erikzimmermann** [comment]
@masmc05 Well I've got test server running with Geyser and floodgate installed but it does not want to work.

I've tried the Geyser API too and have following:
image

So floodgate does not know anything about the Bedrock player and using Geyser I got LinkageErrors due to the dependency management in their libraries...

Any ideas?

**Comment by masmc05** [comment]
> @masmc05 Well I've got a test server running with Geyser and floodgate installed but it does not want to work.
> 
> I've tried the Geyser API too and have following:
> image
> 
> So floodgate does not know anything about the Bedrock player and using Geyser I get LinkageErrors due to the dependency management in their libraries...
> 
> Any ideas?
>  

do you use floodgate auth mode?

**Comment by erikzimmermann** [comment]
No, gonna change it rq.

Please write me on Discord (tag: codingair)

**Comment by FrancescoJacovo** [comment]
guys i'm still having problems between java and bedrock trades. In the last repetition before the trade completitions it breaks as "trade cancelled"

**Pull request merged**
